name: Pocket ID
version: 1.0.2
slug: pocket-id
description: Simple OIDC provider for passkey authentication
url: https://github.com/baggier-rasa/addon-pocket-id
arch:
- amd64
- aarch64
options:
  log_level: info
  APP_URL: http://localhost
  TRUST_PROXY: false
schema:
  log_level: list(debug|info|error)
  APP_URL: str
  TRUST_PROXY: bool
  MAXMIND_LICENSE_KEY: str?
map:
- type: data
  path: /app/data
ports:
  1411/tcp: 1411
init: false
image: ghcr.io/baggier-rasa/pocket-id/{arch}
